-- Roles Table
CREATE TABLE ROLE_ADMIN (
    ROLE_ID INT PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(50) NOT NULL,
    ROLE_POSITION VARCHAR(50)
);

-- Vendor Table
CREATE TABLE VENDOR (
    VENDOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    VENDOR_NAME VARCHAR(100) NOT NULL,
    VENDOR_INFO TEXT,
    CATEGORY_TYPE VARCHAR(50),
    ROLE_ID INT,
    STORE_ID INT, -- Note: Circular dependency if Store also has Vendor. Assuming Vendor -> Store relationship might be 1:1 or 1:N managed here.
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE_ADMIN(ROLE_ID)
);

-- Store Table
CREATE TABLE STORE (
    STORE_ID INT PRIMARY KEY AUTO_INCREMENT,
    STORE_NAME VARCHAR(100) NOT NULL,
    STORE_TYPE VARCHAR(50)
    -- If Store belongs to Vendor, we might expect VENDOR_ID here, but schema shows FK STORE_ID in VENDOR.
    -- We will proceed with the schema as shown, but usually, a Store belongs to a Vendor.
);

-- Category Table
CREATE TABLE CATEGORY (
    CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    CATEGORY_TYPE VARCHAR(50)
);

-- Product Table
CREATE TABLE PRODUCT (
    PRODUCT_ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    PRODUCT_DESC TEXT,
    PRODUCT_PRICE DECIMAL(10, 2) NOT NULL,
    STORE_ID INT,
    CATEGORY_ID INT,
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID)
);

-- Inventory Table
CREATE TABLE INVENTORY (
    INVENTORY_ID INT PRIMARY KEY AUTO_INCREMENT,
    STOCK_QUANTITY INT DEFAULT 0,
    LOW_STOCK_THRESHOLD INT DEFAULT 5,
    PRODUCT_ID INT,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- Customer Table
CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(100) NOT NULL,
    CUSTOMER_NUM VARCHAR(20),
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    MATRIC_No VARCHAR(20),
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE_ID INT,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE_ADMIN(ROLE_ID)
);

-- Status Table
CREATE TABLE STATUS (
    STATUS_ID INT PRIMARY KEY AUTO_INCREMENT,
    STATUS_NAME VARCHAR(50) NOT NULL,
    STATUS_TYPE VARCHAR(50),
    STATUS_DESC TEXT
);

-- Order Table
CREATE TABLE ORDERS ( -- 'ORDER' is a reserved keyword in SQL
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    TOTAL_AMOUNT DECIMAL(10, 2),
    CUSTOMER_ID INT,
    STATUS_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS(STATUS_ID)
);

-- Order Item Table
CREATE TABLE ORDER_ITEM (
    OrderItem_ID INT PRIMARY KEY AUTO_INCREMENT,
    QUANTITY INT NOT NULL,
    SUBTOTAL DECIMAL(10, 2),
    ORDER_ID INT,
    PRODUCT_ID INT,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- Payment Methods Table
CREATE TABLE PAYMENT_METHODS (
    METHOD_ID INT PRIMARY KEY AUTO_INCREMENT,
    Payment_type VARCHAR(50) NOT NULL
);

-- Transaction Table
CREATE TABLE TRANSACTION (
    TRANSACTION_ID INT PRIMARY KEY AUTO_INCREMENT,
    STATUS VARCHAR(50),
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    ORDER_ID INT,
    METHOD_ID INT,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (METHOD_ID) REFERENCES PAYMENT_METHODS(METHOD_ID)
);

-- Service Table
CREATE TABLE SERVICE (
    SERVICE_ID INT PRIMARY KEY AUTO_INCREMENT,
    SERVICE_NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(10, 2),
    STORE_ID INT,
    FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
);

-- TimeSlots Table
CREATE TABLE TIMESLOTS (
    SLOT_ID INT PRIMARY KEY AUTO_INCREMENT,
    START_TIME TIME,
    END_TIME TIME,
    AVAILABLE_SERVICE BOOLEAN,
    SERVICE_ID INT,
    FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID)
);

-- Appointment Table
CREATE TABLE APPOINTMENT (
    APPOINTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    BOOKING_DATE DATE,
    SLOT_ID INT,
    CUSTOMER_ID INT,
    FOREIGN KEY (SLOT_ID) REFERENCES TIMESLOTS(SLOT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- Staff Table
CREATE TABLE STAFF (
    STAFF_ID INT PRIMARY KEY AUTO_INCREMENT,
    STAFF_NAME VARCHAR(100) NOT NULL,
    STAFF_INFO TEXT,
    AVAILABILITY BOOLEAN DEFAULT TRUE,
    VENDOR_ID INT,
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(VENDOR_ID)
);

-- Staff Service Table (Many-to-Many relationship between Staff and Service)
CREATE TABLE STAFF_SERVICE (
    STAFF_ID INT,
    SERVICE_ID INT,
    EXPERIENCE_LEVEL VARCHAR(50),
    SERVICE_PRICE DECIMAL(10, 2),
    PRIMARY KEY (STAFF_ID, SERVICE_ID),
    FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID),
    FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(SERVICE_ID)
);

-- System Logs Table
CREATE TABLE SYSTEM_LOGS (
    LOG_ID INT PRIMARY KEY AUTO_INCREMENT,
    ACTION VARCHAR(255),
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    CUSTOMER_ID INT,
    VENDOR_ID INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (VENDOR_ID) REFERENCES VENDOR(VENDOR_ID)
);
